*Laxmi Charitable Trust’s
Sheth L.U.J College of Arts & Sir M.V. College of Science and Commerce*

*Department of Information Technology* 

**(Bsc.IT Semester III)**

*Python for Data Science Practical*



**Practical - IV**


Roll No. :S032

Name:Niraj Rane

Class :SYIT

Batch : 01

Date of Assignment :05-08-2026

Date/Time of Submission :05-08-2026



In [3]:
import numpy as np


**A]Write a python code to create Numpy Array.**


In [5]:
a = np.array([1,2,3])
print(a)


[1 2 3]


**B]Write a python code to demonstrate basic operations on single array.** 


In [6]:
print(a+2)
print(a*2)

[3 4 5]
[2 4 6]


**C]Write a python code to create array with 10 elements and slice element from 1st to 5th element.**

In [8]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


**D]Write a python code to sort an array alphabetically.**

In [9]:
name = np.array(["Vedant", "Rudra", "Harshal", "Sumeet"])
np.sort(name)

array(['Harshal', 'Rudra', 'Sumeet', 'Vedant'], dtype='<U7')

**E]Write a python code to create a filter array that will return maximum values from an array.**


In [10]:
price =np.array([500,5000,50000,500000])
print(price[price>5000])

[ 50000 500000]
